---

- name: task vault for testing ansible tasks and whatnot
  hosts: all
  gather_facts: yes

  tasks:

  - name: install apache
    dnf:
    name: httpd
    state: latest

  - name: remove apache
    dnf:
    name: httpd
    state: absent
