---

- name: pull some info from postgres and throw it into an html file
  hosts: localhost
  gather_facts: false

  tasks:

    - name: log into the postgres db on controller
      community.postgresql.postgresql_query:
        db: awx
        login_user: '{{ postgres_user }}'
        login_password: '{{ postgres_pass }}'
        query: TABLE main_jobhostsummary
      register: query

    - name: echo query
      debug:
        msg: query
